sudo: required

services:
  - docker

before_install:
  - docker build -t arnaldolucientrindade/sportsconnected ./server

script:
  - docker run arnaldolucientrindade/sportsconnected npm run test -- --coverage