sudo: required

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

services:
  - docker
  - mongodb

before_install:
  - docker build -t arnaldolucientrindade/sportsconnected ./server

before_script:
  - NODE_ENV=test
  - sleep 10

script:
  - npm run test --
