sudo: required

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

env:
  matrix:
    - MONGODB=3.2
    - MONGODB=3.4
    - MONGODB=3.6
    - MONGODB=4.0

services:
  - docker

before_script:
  - docker run -d -p 27017:27017 mongo:$MONGODB

script:
  - MONGODB_URL=mongodb://localhost/connect-mongo-test
  - docker run arnaldolucientrindade/sportsconnected npm run test --

before_install:
  - docker build -t arnaldolucientrindade/sportsconnected ./server

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "sports-connected"
  env: "SportsConnected-env"
  bucket_name: "elasticbeanstalk-us-east-2-697350137372"
  bucket_path: "sports-connected"
  on:
    branch: master-refactor
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
