sudo: required

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

services:
  # - docker
  - mongodb

before_install:
  # - docker build -t arnaldolucientrindade/sportsconnected ./server

env:
  - NODE_ENV=test
  - MONGO_URL=mongodb://localhost:27017/sports_connected

before_script:
  - cd server
  - npm install
  # - mongod --fork --logpath ~/log/mongodb.log
  # - sudo docker-compose stop
  # - sudo docker-compose rm -f
  # - sudo docker-compose up -d || exit 1

script:
  # - docker run arnaldolucientrindade/sportsconnected npm run test --
  - ./scipts/test.sh
  #- npm run test --

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "sports-connected"
  env: "SportsConnected-env"
  bucket_name: "elasticbeanstalk-us-east-2-697350137372"
  bucket_path: "sports-connected"
  on:
    branch: master-refactor
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
