version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:3.3
    command: mongod
    ports:
      - "27017:27017"
    #volumes:
    # - ./data:/data/db

  server:
    container_name: sc-srv
    build: ./server
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - mongo
  # app:
  #  container_name: sc-app
  #  build: ./app
  #  ports:
  #    - "4200:4200"
  # chat:
  # container_name: sc-chat
  # build: ./chat
  # ports:
  #   - "5000:5000"
  # links:
  #   - mongo
#volumes: mongo:
