version: "3.5"
services:
  mongo:
    image: mongo:3.3
    command: mongod

  server:
    container_name: sc-srv
    build: ./server
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - mongo

  app:
    container_name: sc-app
    build: ./app
    ports:
      - "4200:4200"

  chat:
    container_name: sc-chat
    build: ./chat
    ports:
      - "5000:5000"
    links:
      - mongo
